version: '3.1'

services:

  stats-server:
    build: ./stat-service
    container_name: ewm-stat-service_container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats
      - POSTGRES_USER=stats-db-user
      - POSTGRES_PASSWORD=statsdb

  stats-db:
    image: postgres:14-alpine
    container_name: ewm-stats-db_container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm-stats
      - POSTGRES_USER=stats-db-user
      - POSTGRES_PASSWORD=statsdb

  ewm-service:
    build: ./main-service
    container_name: ewm-main-service_container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - APP_NAME=ewm-main-service
      - STAT_SERVER_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-main
      - POSTGRES_USER=main-db-user
      - POSTGRES_PASSWORD=maindb

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-main-db_container
    ports:
      - "8765:5432"
    environment:
      - POSTGRES_DB=ewm-main
      - POSTGRES_USER=main-db-user
      - POSTGRES_PASSWORD=maindb
